# Generated by Django 3.2.7 on 2021-09-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210918_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='employee_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
